// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: report.proto

package com.michaelbutler.grpc.report;

public interface addReportListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.michaelbutler.grpc.report.addReportListRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string report = 1;</code>
   */
  java.lang.String getReport();
  /**
   * <code>string report = 1;</code>
   */
  com.google.protobuf.ByteString
      getReportBytes();
}
