// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: report.proto

package com.michaelbutler.grpc.report;

public interface withdrawReportListReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.michaelbutler.grpc.report.withdrawReportListReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string rReport = 1;</code>
   */
  java.lang.String getRReport();
  /**
   * <code>string rReport = 1;</code>
   */
  com.google.protobuf.ByteString
      getRReportBytes();
}
