# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='payment.proto',
  package='com.michaelbutler.grpc.payment',
  syntax='proto3',
  serialized_options=b'\n\036com.michaelbutler.grpc.paymentB\022paymentServiceImplP\001\242\002\003HLW',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rpayment.proto\x12\x1e\x63om.michaelbutler.grpc.payment\"&\n\x14paymentAmountRequest\x12\x0e\n\x06\x61mount\x18\x01 \x01(\t\"%\n\x12paymentAmountReply\x12\x0f\n\x07rAmount\x18\x01 \x01(\t\"\"\n\x12paymentDateRequest\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\"!\n\x10paymentDateReply\x12\r\n\x05rDate\x18\x01 \x01(\t2\xfd\x01\n\x07Greeter\x12{\n\rpaymentAmount\x12\x34.com.michaelbutler.grpc.payment.paymentAmountRequest\x1a\x32.com.michaelbutler.grpc.payment.paymentAmountReply\"\x00\x12u\n\x0bpaymentDate\x12\x32.com.michaelbutler.grpc.payment.paymentDateRequest\x1a\x30.com.michaelbutler.grpc.payment.paymentDateReply\"\x00\x42<\n\x1e\x63om.michaelbutler.grpc.paymentB\x12paymentServiceImplP\x01\xa2\x02\x03HLWb\x06proto3'
)




_PAYMENTAMOUNTREQUEST = _descriptor.Descriptor(
  name='paymentAmountRequest',
  full_name='com.michaelbutler.grpc.payment.paymentAmountRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='amount', full_name='com.michaelbutler.grpc.payment.paymentAmountRequest.amount', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=87,
)


_PAYMENTAMOUNTREPLY = _descriptor.Descriptor(
  name='paymentAmountReply',
  full_name='com.michaelbutler.grpc.payment.paymentAmountReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rAmount', full_name='com.michaelbutler.grpc.payment.paymentAmountReply.rAmount', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=126,
)


_PAYMENTDATEREQUEST = _descriptor.Descriptor(
  name='paymentDateRequest',
  full_name='com.michaelbutler.grpc.payment.paymentDateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='com.michaelbutler.grpc.payment.paymentDateRequest.date', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=162,
)


_PAYMENTDATEREPLY = _descriptor.Descriptor(
  name='paymentDateReply',
  full_name='com.michaelbutler.grpc.payment.paymentDateReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rDate', full_name='com.michaelbutler.grpc.payment.paymentDateReply.rDate', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=197,
)

DESCRIPTOR.message_types_by_name['paymentAmountRequest'] = _PAYMENTAMOUNTREQUEST
DESCRIPTOR.message_types_by_name['paymentAmountReply'] = _PAYMENTAMOUNTREPLY
DESCRIPTOR.message_types_by_name['paymentDateRequest'] = _PAYMENTDATEREQUEST
DESCRIPTOR.message_types_by_name['paymentDateReply'] = _PAYMENTDATEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

paymentAmountRequest = _reflection.GeneratedProtocolMessageType('paymentAmountRequest', (_message.Message,), {
  'DESCRIPTOR' : _PAYMENTAMOUNTREQUEST,
  '__module__' : 'payment_pb2'
  # @@protoc_insertion_point(class_scope:com.michaelbutler.grpc.payment.paymentAmountRequest)
  })
_sym_db.RegisterMessage(paymentAmountRequest)

paymentAmountReply = _reflection.GeneratedProtocolMessageType('paymentAmountReply', (_message.Message,), {
  'DESCRIPTOR' : _PAYMENTAMOUNTREPLY,
  '__module__' : 'payment_pb2'
  # @@protoc_insertion_point(class_scope:com.michaelbutler.grpc.payment.paymentAmountReply)
  })
_sym_db.RegisterMessage(paymentAmountReply)

paymentDateRequest = _reflection.GeneratedProtocolMessageType('paymentDateRequest', (_message.Message,), {
  'DESCRIPTOR' : _PAYMENTDATEREQUEST,
  '__module__' : 'payment_pb2'
  # @@protoc_insertion_point(class_scope:com.michaelbutler.grpc.payment.paymentDateRequest)
  })
_sym_db.RegisterMessage(paymentDateRequest)

paymentDateReply = _reflection.GeneratedProtocolMessageType('paymentDateReply', (_message.Message,), {
  'DESCRIPTOR' : _PAYMENTDATEREPLY,
  '__module__' : 'payment_pb2'
  # @@protoc_insertion_point(class_scope:com.michaelbutler.grpc.payment.paymentDateReply)
  })
_sym_db.RegisterMessage(paymentDateReply)


DESCRIPTOR._options = None

_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='com.michaelbutler.grpc.payment.Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=200,
  serialized_end=453,
  methods=[
  _descriptor.MethodDescriptor(
    name='paymentAmount',
    full_name='com.michaelbutler.grpc.payment.Greeter.paymentAmount',
    index=0,
    containing_service=None,
    input_type=_PAYMENTAMOUNTREQUEST,
    output_type=_PAYMENTAMOUNTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='paymentDate',
    full_name='com.michaelbutler.grpc.payment.Greeter.paymentDate',
    index=1,
    containing_service=None,
    input_type=_PAYMENTDATEREQUEST,
    output_type=_PAYMENTDATEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
