// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payment.proto

package com.michaelbutler.grpc.payment;

public interface paymentAmountRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.michaelbutler.grpc.payment.paymentAmountRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string amount = 1;</code>
   */
  java.lang.String getAmount();
  /**
   * <code>string amount = 1;</code>
   */
  com.google.protobuf.ByteString
      getAmountBytes();
}
