// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payment.proto

package com.michaelbutler.grpc.payment;

public interface paymentAmountReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.michaelbutler.grpc.payment.paymentAmountReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string rAmount = 1;</code>
   */
  java.lang.String getRAmount();
  /**
   * <code>string rAmount = 1;</code>
   */
  com.google.protobuf.ByteString
      getRAmountBytes();
}
