// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payment.proto

package com.michaelbutler.grpc.payment;

public interface paymentDateReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.michaelbutler.grpc.payment.paymentDateReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string rDate = 1;</code>
   */
  java.lang.String getRDate();
  /**
   * <code>string rDate = 1;</code>
   */
  com.google.protobuf.ByteString
      getRDateBytes();
}
