// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bankAccount.proto

package com.michaelbutler.grpc.bankAccount;

public interface accountBalanceReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.michaelbutler.grpc.bankAccount.accountBalanceReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string rBalance = 1;</code>
   */
  java.lang.String getRBalance();
  /**
   * <code>string rBalance = 1;</code>
   */
  com.google.protobuf.ByteString
      getRBalanceBytes();
}
