// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bankAccount.proto

package com.michaelbutler.grpc.bankAccount;

public interface accountBalanceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.michaelbutler.grpc.bankAccount.accountBalanceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string balance = 1;</code>
   */
  java.lang.String getBalance();
  /**
   * <code>string balance = 1;</code>
   */
  com.google.protobuf.ByteString
      getBalanceBytes();
}
