// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bankAccount.proto

package com.michaelbutler.grpc.bankAccount;

public interface addWithdrawFundsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 balance = 1;</code>
   */
  int getBalance();

  /**
   * <code>int32 transaction = 2;</code>
   */
  int getTransaction();

  /**
   * <code>.com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest.Operation operation = 3;</code>
   */
  int getOperationValue();
  /**
   * <code>.com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest.Operation operation = 3;</code>
   */
  com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest.Operation getOperation();
}
