// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bankAccount.proto

package com.michaelbutler.grpc.bankAccount;

public interface addWithdrawFundsReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.michaelbutler.grpc.bankAccount.addWithdrawFundsReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 newBalance = 1;</code>
   */
  int getNewBalance();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
