// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bankAccount.proto

package com.michaelbutler.grpc.bankAccount;

/**
 * Protobuf type {@code com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest}
 */
public  final class addWithdrawFundsRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest)
    addWithdrawFundsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use addWithdrawFundsRequest.newBuilder() to construct.
  private addWithdrawFundsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private addWithdrawFundsRequest() {
    number1_ = 0F;
    number2_ = 0F;
    operation_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private addWithdrawFundsRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 13: {

            number1_ = input.readFloat();
            break;
          }
          case 21: {

            number2_ = input.readFloat();
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            operation_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.michaelbutler.grpc.bankAccount.BankServiceImpl.internal_static_com_michaelbutler_grpc_bankAccount_addWithdrawFundsRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.michaelbutler.grpc.bankAccount.BankServiceImpl.internal_static_com_michaelbutler_grpc_bankAccount_addWithdrawFundsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest.class, com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest.Builder.class);
  }

  /**
   * Protobuf enum {@code com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest.Operation}
   */
  public enum Operation
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ADD = 0;</code>
     */
    ADD(0),
    /**
     * <code>WITHDRAW = 1;</code>
     */
    WITHDRAW(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ADD = 0;</code>
     */
    public static final int ADD_VALUE = 0;
    /**
     * <code>WITHDRAW = 1;</code>
     */
    public static final int WITHDRAW_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Operation valueOf(int value) {
      return forNumber(value);
    }

    public static Operation forNumber(int value) {
      switch (value) {
        case 0: return ADD;
        case 1: return WITHDRAW;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Operation>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Operation> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Operation>() {
            public Operation findValueByNumber(int number) {
              return Operation.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest.getDescriptor().getEnumTypes().get(0);
    }

    private static final Operation[] VALUES = values();

    public static Operation valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Operation(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest.Operation)
  }

  public static final int NUMBER1_FIELD_NUMBER = 1;
  private float number1_;
  /**
   * <code>float number1 = 1;</code>
   */
  public float getNumber1() {
    return number1_;
  }

  public static final int NUMBER2_FIELD_NUMBER = 2;
  private float number2_;
  /**
   * <code>float number2 = 2;</code>
   */
  public float getNumber2() {
    return number2_;
  }

  public static final int OPERATION_FIELD_NUMBER = 3;
  private int operation_;
  /**
   * <code>.com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest.Operation operation = 3;</code>
   */
  public int getOperationValue() {
    return operation_;
  }
  /**
   * <code>.com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest.Operation operation = 3;</code>
   */
  public com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest.Operation getOperation() {
    @SuppressWarnings("deprecation")
    com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest.Operation result = com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest.Operation.valueOf(operation_);
    return result == null ? com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest.Operation.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (number1_ != 0F) {
      output.writeFloat(1, number1_);
    }
    if (number2_ != 0F) {
      output.writeFloat(2, number2_);
    }
    if (operation_ != com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest.Operation.ADD.getNumber()) {
      output.writeEnum(3, operation_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (number1_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(1, number1_);
    }
    if (number2_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, number2_);
    }
    if (operation_ != com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest.Operation.ADD.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, operation_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest)) {
      return super.equals(obj);
    }
    com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest other = (com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest) obj;

    boolean result = true;
    result = result && (
        java.lang.Float.floatToIntBits(getNumber1())
        == java.lang.Float.floatToIntBits(
            other.getNumber1()));
    result = result && (
        java.lang.Float.floatToIntBits(getNumber2())
        == java.lang.Float.floatToIntBits(
            other.getNumber2()));
    result = result && operation_ == other.operation_;
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NUMBER1_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getNumber1());
    hash = (37 * hash) + NUMBER2_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getNumber2());
    hash = (37 * hash) + OPERATION_FIELD_NUMBER;
    hash = (53 * hash) + operation_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest)
      com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.michaelbutler.grpc.bankAccount.BankServiceImpl.internal_static_com_michaelbutler_grpc_bankAccount_addWithdrawFundsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.michaelbutler.grpc.bankAccount.BankServiceImpl.internal_static_com_michaelbutler_grpc_bankAccount_addWithdrawFundsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest.class, com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest.Builder.class);
    }

    // Construct using com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      number1_ = 0F;

      number2_ = 0F;

      operation_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.michaelbutler.grpc.bankAccount.BankServiceImpl.internal_static_com_michaelbutler_grpc_bankAccount_addWithdrawFundsRequest_descriptor;
    }

    @java.lang.Override
    public com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest getDefaultInstanceForType() {
      return com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest build() {
      com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest buildPartial() {
      com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest result = new com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest(this);
      result.number1_ = number1_;
      result.number2_ = number2_;
      result.operation_ = operation_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest) {
        return mergeFrom((com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest other) {
      if (other == com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest.getDefaultInstance()) return this;
      if (other.getNumber1() != 0F) {
        setNumber1(other.getNumber1());
      }
      if (other.getNumber2() != 0F) {
        setNumber2(other.getNumber2());
      }
      if (other.operation_ != 0) {
        setOperationValue(other.getOperationValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private float number1_ ;
    /**
     * <code>float number1 = 1;</code>
     */
    public float getNumber1() {
      return number1_;
    }
    /**
     * <code>float number1 = 1;</code>
     */
    public Builder setNumber1(float value) {
      
      number1_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float number1 = 1;</code>
     */
    public Builder clearNumber1() {
      
      number1_ = 0F;
      onChanged();
      return this;
    }

    private float number2_ ;
    /**
     * <code>float number2 = 2;</code>
     */
    public float getNumber2() {
      return number2_;
    }
    /**
     * <code>float number2 = 2;</code>
     */
    public Builder setNumber2(float value) {
      
      number2_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float number2 = 2;</code>
     */
    public Builder clearNumber2() {
      
      number2_ = 0F;
      onChanged();
      return this;
    }

    private int operation_ = 0;
    /**
     * <code>.com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest.Operation operation = 3;</code>
     */
    public int getOperationValue() {
      return operation_;
    }
    /**
     * <code>.com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest.Operation operation = 3;</code>
     */
    public Builder setOperationValue(int value) {
      operation_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest.Operation operation = 3;</code>
     */
    public com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest.Operation getOperation() {
      @SuppressWarnings("deprecation")
      com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest.Operation result = com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest.Operation.valueOf(operation_);
      return result == null ? com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest.Operation.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest.Operation operation = 3;</code>
     */
    public Builder setOperation(com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest.Operation value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      operation_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest.Operation operation = 3;</code>
     */
    public Builder clearOperation() {
      
      operation_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest)
  }

  // @@protoc_insertion_point(class_scope:com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest)
  private static final com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest();
  }

  public static com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<addWithdrawFundsRequest>
      PARSER = new com.google.protobuf.AbstractParser<addWithdrawFundsRequest>() {
    @java.lang.Override
    public addWithdrawFundsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new addWithdrawFundsRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<addWithdrawFundsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<addWithdrawFundsRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

