// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bankAccount.proto

package com.michaelbutler.grpc.bankAccount;

public interface addWithdrawFundsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float balance = 1;</code>
   */
  float getBalance();

  /**
   * <code>float transaction = 2;</code>
   */
  float getTransaction();

  /**
   * <code>.com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest.Operation operation = 3;</code>
   */
  int getOperationValue();
  /**
   * <code>.com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest.Operation operation = 3;</code>
   */
  com.michaelbutler.grpc.bankAccount.addWithdrawFundsRequest.Operation getOperation();
}
