// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bankAccount.proto

package com.michaelbutler.grpc.bankAccount;

public final class BankServiceImpl {
  private BankServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_michaelbutler_grpc_bankAccount_accountBalanceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_michaelbutler_grpc_bankAccount_accountBalanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_michaelbutler_grpc_bankAccount_accountBalanceReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_michaelbutler_grpc_bankAccount_accountBalanceReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_michaelbutler_grpc_bankAccount_addWithdrawFundsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_michaelbutler_grpc_bankAccount_addWithdrawFundsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_michaelbutler_grpc_bankAccount_addWithdrawFundsReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_michaelbutler_grpc_bankAccount_addWithdrawFundsReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021bankAccount.proto\022\"com.michaelbutler.g" +
      "rpc.bankAccount\"(\n\025accountBalanceRequest" +
      "\022\017\n\007balance\030\001 \001(\t\"\'\n\023accountBalanceReply" +
      "\022\020\n\010rBalance\030\001 \001(\t\"\271\001\n\027addWithdrawFundsR" +
      "equest\022\017\n\007number1\030\001 \001(\002\022\017\n\007number2\030\002 \001(\002" +
      "\022X\n\toperation\030\003 \001(\0162E.com.michaelbutler." +
      "grpc.bankAccount.addWithdrawFundsRequest" +
      ".Operation\"\"\n\tOperation\022\007\n\003ADD\020\000\022\014\n\010WITH" +
      "DRAW\020\001\"<\n\025addWithdrawFundsReply\022\022\n\nnewBa" +
      "lance\030\001 \001(\002\022\017\n\007message\030\002 \001(\t2\245\002\n\013bankSer" +
      "vice\022\206\001\n\016accountBalance\0229.com.michaelbut" +
      "ler.grpc.bankAccount.accountBalanceReque" +
      "st\0327.com.michaelbutler.grpc.bankAccount." +
      "accountBalanceReply\"\000\022\214\001\n\020addWithdrawFun" +
      "ds\022;.com.michaelbutler.grpc.bankAccount." +
      "addWithdrawFundsRequest\0329.com.michaelbut" +
      "ler.grpc.bankAccount.addWithdrawFundsRep" +
      "ly\"\000B7\n\"com.michaelbutler.grpc.bankAccou" +
      "ntB\017BankServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_michaelbutler_grpc_bankAccount_accountBalanceRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_michaelbutler_grpc_bankAccount_accountBalanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_michaelbutler_grpc_bankAccount_accountBalanceRequest_descriptor,
        new java.lang.String[] { "Balance", });
    internal_static_com_michaelbutler_grpc_bankAccount_accountBalanceReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_michaelbutler_grpc_bankAccount_accountBalanceReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_michaelbutler_grpc_bankAccount_accountBalanceReply_descriptor,
        new java.lang.String[] { "RBalance", });
    internal_static_com_michaelbutler_grpc_bankAccount_addWithdrawFundsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_michaelbutler_grpc_bankAccount_addWithdrawFundsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_michaelbutler_grpc_bankAccount_addWithdrawFundsRequest_descriptor,
        new java.lang.String[] { "Number1", "Number2", "Operation", });
    internal_static_com_michaelbutler_grpc_bankAccount_addWithdrawFundsReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_michaelbutler_grpc_bankAccount_addWithdrawFundsReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_michaelbutler_grpc_bankAccount_addWithdrawFundsReply_descriptor,
        new java.lang.String[] { "NewBalance", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
